//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntelliSenseLocalizer.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IntelliSenseLocalizer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 build the localized intellisense file. 的本地化字符串。
        /// </summary>
        internal static string StringCMDBuildDescription {
            get {
                return ResourceManager.GetString("StringCMDBuildDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 set the content compare type. 的本地化字符串。
        /// </summary>
        internal static string StringCMDBuildOptionContentCompareDescription {
            get {
                return ResourceManager.GetString("StringCMDBuildOptionContentCompareDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 select locale. eg: &quot;zh-cn&quot;. use the system culture info default. 的本地化字符串。
        /// </summary>
        internal static string StringCMDBuildOptionLocaleDescription {
            get {
                return ResourceManager.GetString("StringCMDBuildOptionLocaleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 select .net moniker. eg: &quot;net6.0&quot;. default is all of installed framework. 的本地化字符串。
        /// </summary>
        internal static string StringCMDBuildOptionMonikerDescription {
            get {
                return ResourceManager.GetString("StringCMDBuildOptionMonikerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 set not use existed local page cache. 的本地化字符串。
        /// </summary>
        internal static string StringCMDBuildOptionNoCacheDescription {
            get {
                return ResourceManager.GetString("StringCMDBuildOptionNoCacheDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 set the output path. 的本地化字符串。
        /// </summary>
        internal static string StringCMDBuildOptionOutputDescription {
            get {
                return ResourceManager.GetString("StringCMDBuildOptionOutputDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 select application pack. eg: &quot;Microsoft.AspNetCore.App&quot;. process all pack default.. 的本地化字符串。
        /// </summary>
        internal static string StringCMDBuildOptionPackDescription {
            get {
                return ResourceManager.GetString("StringCMDBuildOptionPackDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 set the parallel process count. large value wiil let MS block your ip fast. 的本地化字符串。
        /// </summary>
        internal static string StringCMDBuildOptionParallelCountDescription {
            get {
                return ResourceManager.GetString("StringCMDBuildOptionParallelCountDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 the separate line between origin and locale content. (effective only use bilingual comparison) 的本地化字符串。
        /// </summary>
        internal static string StringCMDBuildOptionSeparateLineDescription {
            get {
                return ResourceManager.GetString("StringCMDBuildOptionSeparateLineDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 clean the dangling ref folders. 的本地化字符串。
        /// </summary>
        internal static string StringCMDCleanDescription {
            get {
                return ResourceManager.GetString("StringCMDCleanDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 clear the download or cache files. 的本地化字符串。
        /// </summary>
        internal static string StringCMDClearDescription {
            get {
                return ResourceManager.GetString("StringCMDClearDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 try install the localized IntelliSense archive from nuget.org. 的本地化字符串。
        /// </summary>
        internal static string StringCMDInstallAutoInstallDescription {
            get {
                return ResourceManager.GetString("StringCMDInstallAutoInstallDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 select .net moniker. eg: &quot;net6.0&quot;. default is the installed latest version. 的本地化字符串。
        /// </summary>
        internal static string StringCMDInstallAutoOptionMonikerDescription {
            get {
                return ResourceManager.GetString("StringCMDInstallAutoOptionMonikerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 install the localized intellisense file. (from local or online.) 的本地化字符串。
        /// </summary>
        internal static string StringCMDInstallDescription {
            get {
                return ResourceManager.GetString("StringCMDInstallDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 copy the file to the same name package in the Nuget global cache. 的本地化字符串。
        /// </summary>
        internal static string StringCMDInstallOptionCopyToNugetGlobalCacheDescription {
            get {
                return ResourceManager.GetString("StringCMDInstallOptionCopyToNugetGlobalCacheDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 select locale. eg: &quot;zh-cn&quot;. copy all default. 的本地化字符串。
        /// </summary>
        internal static string StringCMDInstallOptionLocaleDescription {
            get {
                return ResourceManager.GetString("StringCMDInstallOptionLocaleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 set the install source file(local or http url). 的本地化字符串。
        /// </summary>
        internal static string StringCMDInstallOptionSourceDescription {
            get {
                return ResourceManager.GetString("StringCMDInstallOptionSourceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 set the install target sdk directory. 的本地化字符串。
        /// </summary>
        internal static string StringCMDInstallOptionTargetDescription {
            get {
                return ResourceManager.GetString("StringCMDInstallOptionTargetDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 query and show more installed SDK info. 的本地化字符串。
        /// </summary>
        internal static string StringCMDShowDescription {
            get {
                return ResourceManager.GetString("StringCMDShowDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 a regex string for filter .net moniker in result. 的本地化字符串。
        /// </summary>
        internal static string StringCMDShowOptionMonikerDescription {
            get {
                return ResourceManager.GetString("StringCMDShowOptionMonikerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 a regex string for filter application pack name in result. 的本地化字符串。
        /// </summary>
        internal static string StringCMDShowOptionPackDescription {
            get {
                return ResourceManager.GetString("StringCMDShowOptionPackDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 list all installed SDK‘s pack refs file. 的本地化字符串。
        /// </summary>
        internal static string StringCMDShowPackRefsDescription {
            get {
                return ResourceManager.GetString("StringCMDShowPackRefsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 list all installed SDK‘s pack. 的本地化字符串。
        /// </summary>
        internal static string StringCMDShowPacksDescription {
            get {
                return ResourceManager.GetString("StringCMDShowPacksDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 select locale. eg: &quot;zh-cn&quot;. 的本地化字符串。
        /// </summary>
        internal static string StringCMDUnInstallArgumentLocaleDescription {
            get {
                return ResourceManager.GetString("StringCMDUnInstallArgumentLocaleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 set the framework moniker. eg: &quot;net6.0&quot; 的本地化字符串。
        /// </summary>
        internal static string StringCMDUnInstallArgumentMonikerDescription {
            get {
                return ResourceManager.GetString("StringCMDUnInstallArgumentMonikerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 uninstall the localized intellisense file. 的本地化字符串。
        /// </summary>
        internal static string StringCMDUnInstallDescription {
            get {
                return ResourceManager.GetString("StringCMDUnInstallDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 set the uninstall target sdk directory. 的本地化字符串。
        /// </summary>
        internal static string StringCMDUnInstallOptionTargetDescription {
            get {
                return ResourceManager.GetString("StringCMDUnInstallOptionTargetDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 islocalizer new version [{0}] found. please use command &apos;dotnet tool update -g islocalizer&apos; to update. 的本地化字符串。
        /// </summary>
        internal static string StringNewVersionFoundTip {
            get {
                return ResourceManager.GetString("StringNewVersionFoundTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 a regex string for filter result. 的本地化字符串。
        /// </summary>
        internal static string StringOptionFilterDescription {
            get {
                return ResourceManager.GetString("StringOptionFilterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 set the log level from 0 - 5 . 的本地化字符串。
        /// </summary>
        internal static string StringOptionLogLevelDescription {
            get {
                return ResourceManager.GetString("StringOptionLogLevelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 a tool to build and install localize intelliSense file
        ///eg:
        ///show Microsoft.NETCore.App for net6.0 contains &apos;threading&apos; xml files:
        ///islocalizer show refs -p Microsoft.NETCore.App -m net6.0 -f threading
        ///
        ///build Microsoft.AspNetCore.App for net6.0 &apos;s localize intelliSense file:
        ///islocalizer build -p Microsoft.AspNetCore.App -m net6.0
        ///
        ///install the builded files (may need run as administrator):
        ///islocalizer install
        ///
        ///clear the build caches:
        ///islocalizer clear cache
        ///
        ///--------------------------------------- [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string StringRootCommandDescription {
            get {
                return ResourceManager.GetString("StringRootCommandDescription", resourceCulture);
            }
        }
    }
}
